### ISSUE TITLE
MontePy Cell Parser gets confused by implicit Union operator of two parenthetical groups

### ISSUE THREAD

**Issue by SterlingButters** [idaholab/MontePy#355]
**Describe the bug**
`Number conflict error: There was a numbering conflict when attempting to add CELL: -2000`

However, it is clear that -2000 is actually a surface in my cell definition albeit, it is the first surface after the continuation indent. Thus, it appears MontePy assumes cell definitions occupy a single line.

**Comment by MicahGale** [comment]
MontePy accepts multi-line horizontal inputs that are preceded by 5 spaces, a tab, or an ampersand. 

This issue is that there are multiple cells -2000 (which shouldn't be allowed #31). So there's something else going on here.

Could you share a minimum ~~working~~ broken example. If it's just cells I usually just change the densities and comments because nothing else can be inferred without the surface and material definitions.

**Comment by SterlingButters** [comment]
@MicahGale In my case `-2000` is a surface ID that accompanies a cell definition. My point was that MontePy shouldn't be trying to add `-2000` as a cell (regardless of any "multiples"). Does the indent have to consist of EXACTLY 5 spaces or can it be more (my case is certainly more to prettily align with the rest of my surfaces)

**Comment by MicahGale** [comment]
So when parsing surfaces in the geometry definition it disregards the negative sign (it actually sets the `ValueNode.is_negetable_identifier = True`, and then reads the absolute value). Yes you are right it accepts 5+ spaces, and 1+ tabs. You can see how it gets tested [here](https://github.com/idaholab/MontePy/blob/5cf1e1ef701218ab6e6c6aa75861bfcc484f1358/tests/test_syntax_parsing.py#L1119).

But back to the point this error isn't from adding a surface to a cell (`cell.surfaces`) but rather adding a cell to `cells` collection (probably `problem.cells`), because it says `CELL: -2000` that's the string representation of a cell, which is the problem child causing the [NumbeConflictError](https://idaholab.github.io/MontePy/api/montepy.errors.html#montepy.errors.NumberConflictError). 

Could you provide more information about what you were doing? Was this just from reading in an input file or were you modifying it?

**Comment by SterlingButters** [comment]
Hmmmm see that is just weird to me since I seem to recall that there was no cell 2000 (let alone a -2000) anywhere in my deck. Moreover, the line number of the input deck (reported in the raised exception) pointed to where -2000 was being added to a cell as a surface post-indent. I'll look at it again on Monday to be absolutely certain. 

I was just reading the input (to answer your question)

**Comment by MicahGale** [comment]
Ok this is very strange. If you can the stack trace alone would be helpful, so the full error log message.

**Comment by SterlingButters** [comment]
@MicahGale its not on an IS that it will be easy to retrieve that from but I'll try to capture the main points here.

**Comment by SterlingButters** [comment]
@MicahGale Interesting! MontePy is in fact not recognizing the indent but only because there was no space for some joined surfaces i.e. I had something like:

```
1    1    -1.0        1000    (-3000:-4000:-5000)(-6000:-7000:8000)
                         -2000    -9000 
```

but when I changed to:
```
1    1    -1.0        1000    (-3000:-4000:-5000)<space here>(-6000:-7000:8000)
                         -2000    -9000 
```

It worked - which is interesting because this isn't fatal in MCNP nor does it change the result.

**Comment by MicahGale** [comment]
Thank you so much this MWE. We can work with this now. This is an interesting one. From what I can remember this is not officially documented, but from a formalism standard MCNP cell syntax is never defined, and is left as being ambiguous. 

Generally I don't want to support undocumented features. At the very least this should have caused a Syntax Error and not this error you experienced, so the error handling needs to be fixed.

I'm just not looking forward to working on the Cell Parser rules. Those are a monstrosity.

**Comment by MicahGale** [comment]
This bug was found again with #452, #453, and so it's now the top development priority. I am hoping to deploy a bug fix by next week.
