### ISSUE TITLE
Material Specifications: cannot unpack non-iterable ValueNode object

### ISSUE THREAD

**Issue by SterlingButters** [idaholab/MontePy#365]
@MicahGale How are material cards supposed to be formatted for MontePy to parse them? I keep getting the error in the subject line. When I inspect the `isotope_fractions` variable in `\data_inputs\material.py`, it is a `ListNode` object containing `ValueNode` objects. For any `ValueNode` object, I see no attribute that corresponds to the isotopic fraction (at least not one intuitively named). Additionally this object is non-iterable so the usage isn't correct either. Am I missing something?

**Comment by MicahGale** [comment]
This seems like a bug most likely. MontePy should be able to handle a material definition as long as the parameters come at the end.

So this should work
``` 
m1 1001.80c 0.33
      8016.80c 0.666667
      plib=80p
```

This syntax breaks it:

``` 
m1 1001.80c 0.33
      plib=80p
      8016.80c 0.666667
```

These object types that you are seeing are data types from the [syntax tree](https://idaholab.github.io/MontePy/api/montepy.input_parser.syntax_node.html). A bad syntax should be handled with syntax errors. So this is definitely odd.

Could you provide an example made up material that causes this bug?

**Comment by SterlingButters** [comment]
Is the `plib` keyword required? I specify my materials like (without `plib`):

```
m1 1001.80c 0.33
      8016.80c 0.666667
```

**Comment by MicahGale** [comment]
No `plib` is not at all required. It was just an example of key-value parameter that you can use. 

That looks like it should work. I'll have to look into this further.

**Comment by SterlingButters** [comment]
I've never used SLY so I'm just throwing ideas at the wall but is the issue possible linked to `_flush_phrase` never being called for the `isotope_fractions` (since `_flush_phrase` is what generates the `ValueNode` - although this doesn't make a `ValueNode` iterable but mahybe you could `zip` the ZAID and fractions `ValueNode`'s)?

**Comment by MicahGale** [comment]
That example code I just dropped in MontePy and it didn't have any issues as I suspected. Could you get us a stack trace and MWE?

As for:

> I've never used SLY so I'm just throwing ideas at the wall but is the issue possibly linked to `_flush_phrase` never being called for the `isotope_fractions` (since `_flush_phrase` is what generates the `ValueNode` - although this doesn't make a `ValueNode` iterable but maybe you could `zip` the ZAID and fractions `ValueNode`'s)?

So `_flush_phrase` isn't a SLY thing, that's just a utility function I made. First [this guide](https://idaholab.github.io/MontePy/developing.html#introduction-to-sly-and-syntax-trees) should give a quick intro to it. Basically `_flush_phrase` is just used for generating `ValueNode` as leaves of the tree quickly. `isotopes_factions` which is of type `IsotopeNode` is a list of pairs of `ValueNode`s that represent the ZAID and then the atom/weight fraction. So the issue is that somehow a `ValueNode` is getting put too high in the syntax tree that the `Material` object as it tries to walk the Syntax Tree is finding it instead of a `IsotopesNode` (which IIRC is a subclass of `ListNode`) for some reason. 

Dynamic typing strikes again.

**Comment by SterlingButters** [comment]
@MicahGale Ahah! Found the issue - I lied to you. I did not, in fact, supply the `abx` suffix - which, as you probably know: 
>If .abx is omitted the first entry from the xsdir file corresponding to the proper library class will
be used. This same approach will be used for all libraries not specified.

**Comment by SterlingButters** [comment]
@MicahGale By the way, are we adding of these to your unit tests (or maybe these aren't worthy)?

**Comment by MicahGale** [comment]
So to confirm the problem is:

```
m1 1001 0.333
    8016 0.6667
```

Yes I know this absolutely valid and can't believe I missed this as a test.

So yes we will absolutely add this to our test suite. [It is the expectation for any bug fixes](https://idaholab.github.io/MontePy/developing.html#merge-checklist). What I will usually do first is write/modify a test to replicate the bug. Ensure that it fails, then push that test to the PR so that way a record of the test failing is preserved. This just makes it nicer for the ~~the reviewer~~ ok really @tjlaboss to verify that the test is effective. I think 100% of the tests in [`tests/test_edge_cases.py`](https://github.com/idaholab/MontePy/blob/develop/tests/test_edge_cases.py) comes from bug reports.

**Comment by MicahGale** [comment]
Error confirmed. Full stack trace:

``` python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[3], line 1
----> 1 material = montepy.data_inputs.material.Material(input)

File ~/dev/montepy/montepy/data_inputs/material.py:40, in Material.__init__(self, input)
     38 set_atom_frac = False
     39 isotope_fractions = self._tree["data"]
---> 40 for isotope_node, fraction in isotope_fractions:
     41     isotope = Isotope(node=isotope_node)
     42     fraction.is_negatable_float = True

TypeError: cannot unpack non-iterable ValueNode object
```
