### ISSUE TITLE
Point all MCNP 6.3 manual links to OSTI

### ISSUE THREAD

**Issue by MicahGale** [idaholab/MontePy#424]
TIL: MCNP 6.3 manual is in fact on OSTI: https://www.osti.gov/biblio/1889957

**Comment by MicahGale** [comment]
In ad-hoc testing osti.gov seems about 2-5x slower than lanl.gov in loading the pdf, which is problematic as a complete load is necessary prior to jumping to an anchor in a pdf.

I'm thinking at the Intro page that we link to the OSTI DOI, and then for `:manual63:` we continue to link to lanl.gov.

Thoughts @tjlaboss?

**Comment by tjlaboss** [comment]
Yes, the documentation should link to the fastest version of the PDF, since the MCNP developers do not foresee supporting HTML documentation at this time.

We can link to the OSTI DOI as a scholarly reference, maybe in `README.me` and the JOSS article, but not for linking to specific sections in the Sphinx docs.
