### ISSUE TITLE
Unit test failure (`test_version`) (v0.4.1)

### ISSUE THREAD

**Issue by jpmorgan98** [idaholab/MontePy#572]
**Describe the bug**

Failed `TestVersion.test_version` when running comprehensive test suite.

**To Reproduce**

`cd MontePy`
`pytest`

**Error Message (if any)**
```
================================================== FAILURES ==================================================
__________________________________________ TestVersion.test_version __________________________________________

self = <tests.test_version.TestVersion testMethod=test_version>

    def test_version(self):
        print(os.path.join("montepy", "_version.py"))
>       self.assertTrue(os.path.exists(os.path.join("montepy", "_version.py")))
E       AssertionError: False is not true

tests/test_version.py:10: AssertionError
-------------------------------------------- Captured stdout call --------------------------------------------
montepy/_version.py
========================================== short test summary info ===========================================
FAILED tests/test_version.py::TestVersion::test_version - AssertionError: False is not true
```

**Version**

 - Version 0.4.1 with optional testing dependencies (`pip install 'montepy[test]'`)
 - Python 3.12.3

**Additional context**

[Part of pyOpenSci review!](https://github.com/pyOpenSci/software-submission/issues/205)

**Comment by MicahGale** [comment]
Currently the version string is generated by `setuptools_scm` on deploy by writing `montepy/_version.py`. This inherently means that `_version.py` can't be tracked and isn't cloned. Due to this [`montepy/__init__.py`](https://github.com/idaholab/MontePy/blob/develop/montepy/__init__.py) has three ways to determine the version. This test is trying to verify all three methods work. It assumes that `_version.py` is there. The weird thing is that in CI I can't see where this file is coming from, and it shouldn't be passing?

This test just needs to be updated to ensure that `setuptools_scm` generates that file. 

A temporary workaround would be to run `python -m build .`
